### ISSUE TITLE
Empty recording?

### ISSUE THREAD

**Issue by uwestephan1975** [mickekring/Diane#1]
Hi Micke

When I stop the recording in "Diane" the app seems to store an **empty** audio-file in the audio folder. Whisper can then not transcribe anything an ChatGPT wonders what it should summarize. 

I'm a little new to python on the MacOS. Is that anything that you have experienced when coding? Or is it a setting on my side?

Thank you in advance!
Best regards 
Uwe

**Comment by uwestephan1975** [comment]
Ity was the privacy settings of macOS that prohibited to use the microton via a python script that runs in IDLE. It worked when I switched to run the code in Terminal. Then I got a popup to grant microton access for Terminal.

**Comment by mickekring** [comment]
Ah, thanks for pointing that out. I'll add it to the readme. More people will run into this if they haven't run python code on their computer before.

**Comment by mickekring** [comment]
I'm closing this issue.

**Comment by mickekring** [comment]
I'm closing this issue.
